# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Luis J. Centeno
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a Web developer and this is my personal web page, i talk about software development and my personal projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://luishck.github.io" # the base hostname & protocol for your site, e.g. http://example.com
cover: andromeda.jpg
logo: logo.png

# Your skills
skills:
  backend:
    - Ruby On Rails
    - Django
    - NodeJS
  frontend:
    - VueJS
    - ReactJS
    - Angular
  mobile:
    - Ionic
    - Progresive Web Apps
    - Android Studio
  desktop:
    - Visual Studio
    - ElectronJS

social:
  github: luishck
  twitter: luishck
  facebook: LuisHCKv0.1
  email: luisjcenteno@live.com

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
sass:
    sass_dir: _sass
